image: docker:latest
services:
  - docker:dind

before_script:
  
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install docker-compose


build:
    stage: build
    script:

        - docker image  prune -f
        - docker-compose -f docker-compose.yml build --no-cache
        - docker-compose -f docker-compose.yml up -d


